[2023-03-02T00:21:17.943+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: metadata_scraper.scrape_goes_data scheduled__2023-03-01T00:00:00+00:00 [queued]>
[2023-03-02T00:21:18.082+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: metadata_scraper.scrape_goes_data scheduled__2023-03-01T00:00:00+00:00 [queued]>
[2023-03-02T00:21:18.095+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-02T00:21:18.101+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-02T00:21:18.108+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-02T00:21:18.611+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): scrape_goes_data> on 2023-03-01 00:00:00+00:00
[2023-03-02T00:21:20.355+0000] {standard_task_runner.py:55} INFO - Started process 1954 to run task
[2023-03-02T00:21:21.210+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'metadata_scraper', 'scrape_goes_data', 'scheduled__2023-03-01T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/scrapper.py', '--cfg-path', '/tmp/tmp8p892ugw']
[2023-03-02T00:21:22.455+0000] {standard_task_runner.py:83} INFO - Job 6: Subtask scrape_goes_data
[2023-03-02T00:21:30.477+0000] {task_command.py:388} INFO - Running <TaskInstance: metadata_scraper.scrape_goes_data scheduled__2023-03-01T00:00:00+00:00 [running]> on host 03892a27b5ab
[2023-03-02T00:22:28.914+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Charu Singh
AIRFLOW_CTX_DAG_ID=metadata_scraper
AIRFLOW_CTX_TASK_ID=scrape_goes_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-01T00:00:00+00:00
[2023-03-02T00:22:34.272+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scrapper.py", line 38, in GOES_scrap_load
    result = s3.list_objects(Bucket=goes_bucket, Prefix=prefix, Delimiter='/')
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 944, in _make_api_call
    operation_model, request_dict, request_context
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 966, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/endpoint.py", line 198, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/endpoint.py", line 137, in create_request
    operation_name=operation_model.name,
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/signers.py", line 105, in handler
    return self.sign(operation_name, request)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/signers.py", line 189, in sign
    auth.add_auth(request)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/auth.py", line 418, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
[2023-03-02T00:22:53.850+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=metadata_scraper, task_id=scrape_goes_data, execution_date=20230301T000000, start_date=20230302T002118, end_date=20230302T002248
[2023-03-02T00:23:03.611+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 6 for task scrape_goes_data (Unable to locate credentials; 1954)
[2023-03-02T00:23:17.209+0000] {local_task_job.py:273} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-03-02T00:23:18.535+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 1954. PIDs of all processes in the group: [1954]
[2023-03-02T00:23:18.610+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 1954
[2023-03-02T00:23:25.640+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1954, status='terminated', exitcode=1, started='00:21:19') (1954) terminated with exit code 1
[2023-03-02T02:09:43.344+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: metadata_scraper.scrape_goes_data scheduled__2023-03-01T00:00:00+00:00 [queued]>
[2023-03-02T02:09:43.358+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: metadata_scraper.scrape_goes_data scheduled__2023-03-01T00:00:00+00:00 [queued]>
[2023-03-02T02:09:43.359+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-02T02:09:43.360+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-02T02:09:43.360+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-02T02:09:43.373+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): scrape_goes_data> on 2023-03-01 00:00:00+00:00
[2023-03-02T02:09:43.384+0000] {standard_task_runner.py:55} INFO - Started process 255 to run task
[2023-03-02T02:09:43.391+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'metadata_scraper', 'scrape_goes_data', 'scheduled__2023-03-01T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/scrapper.py', '--cfg-path', '/tmp/tmpvoy2oviy']
[2023-03-02T02:09:43.400+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask scrape_goes_data
[2023-03-02T02:09:43.544+0000] {task_command.py:388} INFO - Running <TaskInstance: metadata_scraper.scrape_goes_data scheduled__2023-03-01T00:00:00+00:00 [running]> on host 5d83bf79023b
[2023-03-02T02:09:43.653+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Charu Singh
AIRFLOW_CTX_DAG_ID=metadata_scraper
AIRFLOW_CTX_TASK_ID=scrape_goes_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-01T00:00:00+00:00
[2023-03-02T02:10:01.720+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-03-02T02:10:01.766+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=metadata_scraper, task_id=scrape_goes_data, execution_date=20230301T000000, start_date=20230302T020943, end_date=20230302T021001
[2023-03-02T02:10:01.871+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-03-02T02:10:01.909+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
