[2023-02-23T02:28:49.627+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: metadata_to_db.sql_script_goes manual__2023-02-23T02:28:46.974196+00:00 [queued]>
[2023-02-23T02:28:49.658+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: metadata_to_db.sql_script_goes manual__2023-02-23T02:28:46.974196+00:00 [queued]>
[2023-02-23T02:28:49.660+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-23T02:28:49.661+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-02-23T02:28:49.662+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-23T02:28:49.674+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): sql_script_goes> on 2023-02-23 02:28:46.974196+00:00
[2023-02-23T02:28:49.710+0000] {standard_task_runner.py:55} INFO - Started process 17347 to run task
[2023-02-23T02:28:49.736+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'metadata_to_db', 'sql_script_goes', 'manual__2023-02-23T02:28:46.974196+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/schedule.py', '--cfg-path', '/tmp/tmpdn0wgu62']
[2023-02-23T02:28:49.740+0000] {standard_task_runner.py:83} INFO - Job 39: Subtask sql_script_goes
[2023-02-23T02:28:49.862+0000] {task_command.py:388} INFO - Running <TaskInstance: metadata_to_db.sql_script_goes manual__2023-02-23T02:28:46.974196+00:00 [running]> on host fd37b4f3bb6b
[2023-02-23T02:28:49.981+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Charu Singh
AIRFLOW_CTX_DAG_ID=metadata_to_db
AIRFLOW_CTX_TASK_ID=sql_script_goes
AIRFLOW_CTX_EXECUTION_DATE=2023-02-23T02:28:46.974196+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-23T02:28:46.974196+00:00
[2023-02-23T02:28:49.989+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-02-23T02:28:49.993+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python ./sql_goes.py']
[2023-02-23T02:28:50.045+0000] {subprocess.py:86} INFO - Output:
[2023-02-23T02:28:50.142+0000] {subprocess.py:93} INFO - python: can't open file './sql_goes.py': [Errno 2] No such file or directory
[2023-02-23T02:28:50.145+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-02-23T02:28:50.162+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-02-23T02:28:50.172+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=metadata_to_db, task_id=sql_script_goes, execution_date=20230223T022846, start_date=20230223T022849, end_date=20230223T022850
[2023-02-23T02:28:50.205+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 39 for task sql_script_goes (Bash command failed. The command returned a non-zero exit code 2.; 17347)
[2023-02-23T02:28:50.273+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-23T02:28:50.356+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
