[2023-02-23T03:11:20.378+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: database_dag.get_meta_data_for_db_population manual__2023-02-23T03:11:11+00:00 [queued]>
[2023-02-23T03:11:20.392+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: database_dag.get_meta_data_for_db_population manual__2023-02-23T03:11:11+00:00 [queued]>
[2023-02-23T03:11:20.393+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-23T03:11:20.404+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-02-23T03:11:20.405+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-23T03:11:20.414+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): get_meta_data_for_db_population> on 2023-02-23 03:11:11+00:00
[2023-02-23T03:11:20.430+0000] {standard_task_runner.py:55} INFO - Started process 19952 to run task
[2023-02-23T03:11:20.440+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'database_dag', 'get_meta_data_for_db_population', 'manual__2023-02-23T03:11:11+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/metadataScrapper.py', '--cfg-path', '/tmp/tmpussgxjn2']
[2023-02-23T03:11:20.441+0000] {standard_task_runner.py:83} INFO - Job 46: Subtask get_meta_data_for_db_population
[2023-02-23T03:11:20.563+0000] {task_command.py:388} INFO - Running <TaskInstance: database_dag.get_meta_data_for_db_population manual__2023-02-23T03:11:11+00:00 [running]> on host fd37b4f3bb6b
[2023-02-23T03:11:20.678+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Charu Singh
AIRFLOW_CTX_DAG_ID=database_dag
AIRFLOW_CTX_TASK_ID=get_meta_data_for_db_population
AIRFLOW_CTX_EXECUTION_DATE=2023-02-23T03:11:11+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-23T03:11:11+00:00
[2023-02-23T03:11:20.804+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/metadataScrapper.py", line 146, in get_meta_data_for_db_population
    files = get_files_from_noaa_bucket("ABI-L1b-RadC")
  File "/opt/airflow/dags/metadataScrapper.py", line 131, in get_files_from_noaa_bucket
    for count,page in enumerate(noaa_bucket):
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/paginate.py", line 269, in __iter__
    response = self._make_request(current_kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/paginate.py", line 357, in _make_request
    return self._method(**current_kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 944, in _make_api_call
    operation_model, request_dict, request_context
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 966, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/endpoint.py", line 198, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/endpoint.py", line 137, in create_request
    operation_name=operation_model.name,
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/signers.py", line 105, in handler
    return self.sign(operation_name, request)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/signers.py", line 189, in sign
    auth.add_auth(request)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/auth.py", line 418, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
[2023-02-23T03:11:20.833+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=database_dag, task_id=get_meta_data_for_db_population, execution_date=20230223T031111, start_date=20230223T031120, end_date=20230223T031120
[2023-02-23T03:11:20.845+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 46 for task get_meta_data_for_db_population (Unable to locate credentials; 19952)
[2023-02-23T03:11:20.902+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-23T03:11:20.945+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
