[2023-02-23T23:15:29.372+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: database_to_csv.export_to_csv manual__2023-02-23T23:15:26.209203+00:00 [queued]>
[2023-02-23T23:15:29.382+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: database_to_csv.export_to_csv manual__2023-02-23T23:15:26.209203+00:00 [queued]>
[2023-02-23T23:15:29.383+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-23T23:15:29.388+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-02-23T23:15:29.389+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-23T23:15:29.400+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): export_to_csv> on 2023-02-23 23:15:26.209203+00:00
[2023-02-23T23:15:29.411+0000] {standard_task_runner.py:55} INFO - Started process 5161 to run task
[2023-02-23T23:15:29.417+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'database_to_csv', 'export_to_csv', 'manual__2023-02-23T23:15:26.209203+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/metadataScrapper.py', '--cfg-path', '/tmp/tmpy8u4mmco']
[2023-02-23T23:15:29.419+0000] {standard_task_runner.py:83} INFO - Job 20: Subtask export_to_csv
[2023-02-23T23:15:29.515+0000] {task_command.py:388} INFO - Running <TaskInstance: database_to_csv.export_to_csv manual__2023-02-23T23:15:26.209203+00:00 [running]> on host e71d177a0fdc
[2023-02-23T23:15:29.596+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Charu Singh
AIRFLOW_CTX_DAG_ID=database_to_csv
AIRFLOW_CTX_TASK_ID=export_to_csv
AIRFLOW_CTX_EXECUTION_DATE=2023-02-23T23:15:26.209203+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-23T23:15:26.209203+00:00
[2023-02-23T23:15:29.605+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/metadataScrapper.py", line 151, in database_to_csv
    cur.execute("SELECT * FROM metadata_goes18")
sqlite3.OperationalError: no such table: metadata_goes18
[2023-02-23T23:15:29.645+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=database_to_csv, task_id=export_to_csv, execution_date=20230223T231526, start_date=20230223T231529, end_date=20230223T231529
[2023-02-23T23:15:29.673+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 20 for task export_to_csv (no such table: metadata_goes18; 5161)
[2023-02-23T23:15:29.710+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-23T23:15:29.737+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
