[2023-02-23T04:32:58.799+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: database_dag.initialize_db manual__2023-02-23T04:32:54.979511+00:00 [queued]>
[2023-02-23T04:32:58.808+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: database_dag.initialize_db manual__2023-02-23T04:32:54.979511+00:00 [queued]>
[2023-02-23T04:32:58.809+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-23T04:32:58.813+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-02-23T04:32:58.814+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-23T04:32:58.823+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): initialize_db> on 2023-02-23 04:32:54.979511+00:00
[2023-02-23T04:32:58.843+0000] {standard_task_runner.py:55} INFO - Started process 20900 to run task
[2023-02-23T04:32:58.851+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'database_dag', 'initialize_db', 'manual__2023-02-23T04:32:54.979511+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/metadataScrapper.py', '--cfg-path', '/tmp/tmpihevhsfo']
[2023-02-23T04:32:58.854+0000] {standard_task_runner.py:83} INFO - Job 52: Subtask initialize_db
[2023-02-23T04:32:58.953+0000] {task_command.py:388} INFO - Running <TaskInstance: database_dag.initialize_db manual__2023-02-23T04:32:54.979511+00:00 [running]> on host fd37b4f3bb6b
[2023-02-23T04:32:59.014+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Charu Singh
AIRFLOW_CTX_DAG_ID=database_dag
AIRFLOW_CTX_TASK_ID=initialize_db
AIRFLOW_CTX_EXECUTION_DATE=2023-02-23T04:32:54.979511+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-23T04:32:54.979511+00:00
[2023-02-23T04:32:59.017+0000] {logging_mixin.py:137} INFO - /opt/***/dags
[2023-02-23T04:32:59.018+0000] {metadataScrapper.py:109} INFO - Database file already exist
[2023-02-23T04:33:01.083+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/metadataScrapper.py", line 110, in check_database_initilization
    create_table_in_db()
  File "/opt/airflow/dags/metadataScrapper.py", line 90, in create_table_in_db
    df = create_df()
  File "/opt/airflow/dags/metadataScrapper.py", line 80, in create_df
    data = get_meta_data_for_db_population()
  File "/opt/airflow/dags/metadataScrapper.py", line 142, in get_meta_data_for_db_population
    files = get_files_from_goes_bucket("ABI-L1b-RadC")
  File "/opt/airflow/dags/metadataScrapper.py", line 130, in get_files_from_goes_bucket
    goes_bucket = paginator.paginate(Bucket = goes_bucket,Prefix = dir)
UnboundLocalError: local variable 'goes_bucket' referenced before assignment
[2023-02-23T04:33:01.104+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=database_dag, task_id=initialize_db, execution_date=20230223T043254, start_date=20230223T043258, end_date=20230223T043301
[2023-02-23T04:33:01.122+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 52 for task initialize_db (local variable 'goes_bucket' referenced before assignment; 20900)
[2023-02-23T04:33:01.179+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-23T04:33:01.209+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
