[2023-02-23T04:38:02.807+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: database_dag.initialize_db manual__2023-02-23T04:32:54.979511+00:00 [queued]>
[2023-02-23T04:38:02.815+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: database_dag.initialize_db manual__2023-02-23T04:32:54.979511+00:00 [queued]>
[2023-02-23T04:38:02.816+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-23T04:38:02.817+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2023-02-23T04:38:02.818+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-23T04:38:02.828+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): initialize_db> on 2023-02-23 04:32:54.979511+00:00
[2023-02-23T04:38:02.841+0000] {standard_task_runner.py:55} INFO - Started process 21206 to run task
[2023-02-23T04:38:02.846+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'database_dag', 'initialize_db', 'manual__2023-02-23T04:32:54.979511+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/metadataScrapper.py', '--cfg-path', '/tmp/tmphuuj66e7']
[2023-02-23T04:38:02.851+0000] {standard_task_runner.py:83} INFO - Job 54: Subtask initialize_db
[2023-02-23T04:38:02.951+0000] {task_command.py:388} INFO - Running <TaskInstance: database_dag.initialize_db manual__2023-02-23T04:32:54.979511+00:00 [running]> on host fd37b4f3bb6b
[2023-02-23T04:38:03.024+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Charu Singh
AIRFLOW_CTX_DAG_ID=database_dag
AIRFLOW_CTX_TASK_ID=initialize_db
AIRFLOW_CTX_EXECUTION_DATE=2023-02-23T04:32:54.979511+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-23T04:32:54.979511+00:00
[2023-02-23T04:38:03.027+0000] {logging_mixin.py:137} INFO - /opt/***/dags
[2023-02-23T04:38:03.030+0000] {metadataScrapper.py:107} INFO - Database file already exist
[2023-02-23T04:38:03.545+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/metadataScrapper.py", line 108, in check_database_initilization
    create_table_in_db()
  File "/opt/airflow/dags/metadataScrapper.py", line 88, in create_table_in_db
    df = create_df()
  File "/opt/airflow/dags/metadataScrapper.py", line 78, in create_df
    data = get_meta_data_for_db_population()
  File "/opt/airflow/dags/metadataScrapper.py", line 140, in get_meta_data_for_db_population
    files = get_files_from_goes_bucket("ABI-L1b-RadC")
  File "/opt/airflow/dags/metadataScrapper.py", line 128, in get_files_from_goes_bucket
    goes_bucket = paginator.paginate(Bucket = goes_bucket,Prefix = dir)
UnboundLocalError: local variable 'goes_bucket' referenced before assignment
[2023-02-23T04:38:03.585+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=database_dag, task_id=initialize_db, execution_date=20230223T043254, start_date=20230223T043802, end_date=20230223T043803
[2023-02-23T04:38:03.604+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 54 for task initialize_db (local variable 'goes_bucket' referenced before assignment; 21206)
[2023-02-23T04:38:03.677+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-23T04:38:03.736+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
