[2023-03-02T01:05:02.394+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: metadata_scraper.scrape_goes_data manual__2023-03-02T01:04:59.855182+00:00 [queued]>
[2023-03-02T01:05:02.400+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: metadata_scraper.scrape_goes_data manual__2023-03-02T01:04:59.855182+00:00 [queued]>
[2023-03-02T01:05:02.401+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-02T01:05:02.402+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-02T01:05:02.411+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-02T01:05:02.422+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): scrape_goes_data> on 2023-03-02 01:04:59.855182+00:00
[2023-03-02T01:05:02.458+0000] {standard_task_runner.py:55} INFO - Started process 1816 to run task
[2023-03-02T01:05:02.466+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'metadata_scraper', 'scrape_goes_data', 'manual__2023-03-02T01:04:59.855182+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/scrapper.py', '--cfg-path', '/tmp/tmpsmoq9j70']
[2023-03-02T01:05:02.472+0000] {standard_task_runner.py:83} INFO - Job 16: Subtask scrape_goes_data
[2023-03-02T01:05:02.648+0000] {task_command.py:388} INFO - Running <TaskInstance: metadata_scraper.scrape_goes_data manual__2023-03-02T01:04:59.855182+00:00 [running]> on host e05f699ebc35
[2023-03-02T01:05:02.724+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Charu Singh
AIRFLOW_CTX_DAG_ID=metadata_scraper
AIRFLOW_CTX_TASK_ID=scrape_goes_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-02T01:04:59.855182+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-02T01:04:59.855182+00:00
[2023-03-02T01:05:20.846+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scrapper.py", line 79, in GOES_scrap_load
    (row['id'], row['product'], row['year'], row['day'], row['hour']))
TypeError: tuple indices must be integers or slices, not str
[2023-03-02T01:05:20.924+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=metadata_scraper, task_id=scrape_goes_data, execution_date=20230302T010459, start_date=20230302T010502, end_date=20230302T010520
[2023-03-02T01:05:20.951+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 16 for task scrape_goes_data (tuple indices must be integers or slices, not str; 1816)
[2023-03-02T01:05:21.002+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-02T01:05:21.098+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
