[2023-02-23T02:42:01.775+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: metadata_to_db.sql_script_goes manual__2023-02-23T02:41:59.384549+00:00 [queued]>
[2023-02-23T02:42:01.786+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: metadata_to_db.sql_script_goes manual__2023-02-23T02:41:59.384549+00:00 [queued]>
[2023-02-23T02:42:01.788+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-23T02:42:01.790+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-02-23T02:42:01.792+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-23T02:42:01.802+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): sql_script_goes> on 2023-02-23 02:41:59.384549+00:00
[2023-02-23T02:42:01.832+0000] {standard_task_runner.py:55} INFO - Started process 18157 to run task
[2023-02-23T02:42:01.837+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'metadata_to_db', 'sql_script_goes', 'manual__2023-02-23T02:41:59.384549+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/schedule.py', '--cfg-path', '/tmp/tmpxc2fle_1']
[2023-02-23T02:42:01.839+0000] {standard_task_runner.py:83} INFO - Job 40: Subtask sql_script_goes
[2023-02-23T02:42:01.930+0000] {task_command.py:388} INFO - Running <TaskInstance: metadata_to_db.sql_script_goes manual__2023-02-23T02:41:59.384549+00:00 [running]> on host fd37b4f3bb6b
[2023-02-23T02:42:01.995+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Charu Singh
AIRFLOW_CTX_DAG_ID=metadata_to_db
AIRFLOW_CTX_TASK_ID=sql_script_goes
AIRFLOW_CTX_EXECUTION_DATE=2023-02-23T02:41:59.384549+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-23T02:41:59.384549+00:00
[2023-02-23T02:42:02.004+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-02-23T02:42:02.006+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python sql_goes.py']
[2023-02-23T02:42:02.020+0000] {subprocess.py:86} INFO - Output:
[2023-02-23T02:42:02.104+0000] {subprocess.py:93} INFO - python: can't open file 'sql_goes.py': [Errno 2] No such file or directory
[2023-02-23T02:42:02.107+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-02-23T02:42:02.119+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-02-23T02:42:02.123+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=metadata_to_db, task_id=sql_script_goes, execution_date=20230223T024159, start_date=20230223T024201, end_date=20230223T024202
[2023-02-23T02:42:02.133+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 40 for task sql_script_goes (Bash command failed. The command returned a non-zero exit code 2.; 18157)
[2023-02-23T02:42:02.178+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-23T02:42:02.200+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
