[2023-02-23T18:30:21.921+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: metadata_scraper.scrape_goes_data manual__2023-02-23T18:30:19.660507+00:00 [queued]>
[2023-02-23T18:30:21.946+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: metadata_scraper.scrape_goes_data manual__2023-02-23T18:30:19.660507+00:00 [queued]>
[2023-02-23T18:30:21.947+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-23T18:30:21.949+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-02-23T18:30:21.950+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-23T18:30:21.966+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): scrape_goes_data> on 2023-02-23 18:30:19.660507+00:00
[2023-02-23T18:30:21.977+0000] {standard_task_runner.py:55} INFO - Started process 108 to run task
[2023-02-23T18:30:21.984+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'metadata_scraper', 'scrape_goes_data', 'manual__2023-02-23T18:30:19.660507+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/metadataScrapper.py', '--cfg-path', '/tmp/tmpp2lwlm18']
[2023-02-23T18:30:21.993+0000] {standard_task_runner.py:83} INFO - Job 73: Subtask scrape_goes_data
[2023-02-23T18:30:22.083+0000] {task_command.py:388} INFO - Running <TaskInstance: metadata_scraper.scrape_goes_data manual__2023-02-23T18:30:19.660507+00:00 [running]> on host a63d292ab6ab
[2023-02-23T18:30:22.208+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Charu Singh
AIRFLOW_CTX_DAG_ID=metadata_scraper
AIRFLOW_CTX_TASK_ID=scrape_goes_data
AIRFLOW_CTX_EXECUTION_DATE=2023-02-23T18:30:19.660507+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-23T18:30:19.660507+00:00
[2023-02-23T18:30:22.214+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/metadataScrapper.py", line 38, in goes18_data
    for root, dirs, files in os.walk(os.environ.get(goes_bucket)):
  File "/usr/local/lib/python3.7/os.py", line 339, in walk
    top = fspath(top)
TypeError: expected str, bytes or os.PathLike object, not NoneType
[2023-02-23T18:30:22.230+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=metadata_scraper, task_id=scrape_goes_data, execution_date=20230223T183019, start_date=20230223T183021, end_date=20230223T183022
[2023-02-23T18:30:22.247+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 73 for task scrape_goes_data (expected str, bytes or os.PathLike object, not NoneType; 108)
[2023-02-23T18:30:22.287+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-23T18:30:22.316+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
