[2023-02-23T22:52:53.840+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: metadata_scraper.scrape_goes_data manual__2023-02-23T22:52:49.533112+00:00 [queued]>
[2023-02-23T22:52:53.850+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: metadata_scraper.scrape_goes_data manual__2023-02-23T22:52:49.533112+00:00 [queued]>
[2023-02-23T22:52:53.851+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-23T22:52:53.854+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-02-23T22:52:53.855+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-23T22:52:53.867+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): scrape_goes_data> on 2023-02-23 22:52:49.533112+00:00
[2023-02-23T22:52:53.886+0000] {standard_task_runner.py:55} INFO - Started process 3751 to run task
[2023-02-23T22:52:53.895+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'metadata_scraper', 'scrape_goes_data', 'manual__2023-02-23T22:52:49.533112+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/metadataScrapper.py', '--cfg-path', '/tmp/tmpgb53d_iw']
[2023-02-23T22:52:53.898+0000] {standard_task_runner.py:83} INFO - Job 14: Subtask scrape_goes_data
[2023-02-23T22:52:54.036+0000] {task_command.py:388} INFO - Running <TaskInstance: metadata_scraper.scrape_goes_data manual__2023-02-23T22:52:49.533112+00:00 [running]> on host e71d177a0fdc
[2023-02-23T22:52:54.110+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Charu Singh
AIRFLOW_CTX_DAG_ID=metadata_scraper
AIRFLOW_CTX_TASK_ID=scrape_goes_data
AIRFLOW_CTX_EXECUTION_DATE=2023-02-23T22:52:49.533112+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-23T22:52:49.533112+00:00
[2023-02-23T22:52:54.122+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/metadataScrapper.py", line 40, in GOES_scrap_load
    Prefix= 'ABI-L1b-RadC/', Delimiter='/')
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 944, in _make_api_call
    operation_model, request_dict, request_context
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 966, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/endpoint.py", line 198, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/endpoint.py", line 137, in create_request
    operation_name=operation_model.name,
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/signers.py", line 105, in handler
    return self.sign(operation_name, request)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/signers.py", line 189, in sign
    auth.add_auth(request)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/auth.py", line 418, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
[2023-02-23T22:52:54.143+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=metadata_scraper, task_id=scrape_goes_data, execution_date=20230223T225249, start_date=20230223T225253, end_date=20230223T225254
[2023-02-23T22:52:54.153+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 14 for task scrape_goes_data (Unable to locate credentials; 3751)
[2023-02-23T22:52:54.199+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-23T22:52:54.240+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
